- name: Initial Machine Setup (Update, Upgrade, Install Packages)
  hosts: localhost

  vars:
    nvim_install_dir: /opt/nvim # Directory where Neovim will be installed
    alacritty_version: 0.13.0 # Specify the desired version
    alacritty_release_url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_version }}/alacritty-linux-x86_64-unknown-linux-gnu.tar.gz"
    alacritty_install_dir: /opt/alacritty # Where to install the files

  tasks:
    - name: Upgrade all installed packages
      become: yes
      apt:
        upgrade: yes
      tags:
        - packages
        - update

    - name: Install common utilities and development packages
      become: yes
      apt:
        name:
          - git
          - build-essential # Essential for compiling software
          - nano # Another common text editor
          - curl
          - vim
          - htop
          - tmux
          - fzf
          - ripgrep
          - i3
          - stow
          - feh
          - pavucontrol
          - arandr
          - zsh
          - autorandr
          - xsel
          - xclip
          - cmake
          - g++
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
          - jq
          - libgtk-4-dev
          - libadwaita-1-dev
          - blueprint-compiler
          - gettext
          - libxml2-utils
          - maim
        state: present
      tags:
        - packages
        - install
    - name: Import Neovim installation tasks
      become: yes
      import_tasks: nvim.yaml
      tags:
        - packages
        - nvim
    - name: Import golang installation tasks
      import_tasks: go.yaml
      become: yes
      tags:
        - packages
        - golang
    - name: Install elastic vue
      import_tasks: elasticvue.yaml
      tags:
        - packages
        - elasticvue
    - name: Install gcloud cli
      import_tasks: gcpCli.yaml
      tags:
        - packages
        - gcpCli
    - name: Install docker cli
      become: yes
      import_tasks: docker.yaml
      tags:
        - packages
        - docker
    - name: Import ziglang installation tasks
      import_tasks: zig.yaml
      become: yes
      tags:
        - packages
        - zig
    - name: Install steam latest
      import_tasks: steam.yaml
      tags:
        - packages
        - steam
    - name: Install vscode latest
      import_tasks: vscode.yaml
      tags:
        - packages
        - vscode
    - name: Install slack latest
      import_tasks: slack.yaml
      tags:
        - packages
        - slack
    - name: Install Brave Browser using the official script
      shell: |
        curl -fsS https://dl.brave.com/install.sh | sh
      args:
        executable: /bin/bash # Ensure it runs with bash
        creates: /usr/bin/brave-browser # Make this task idempotent - check if brave-browser executable exists
      tags:
        - brave
        - browser
    - name: Install Rust using rustup.rs script
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        executable: /bin/bash
        creates: "$HOME/.rustup/bin/rustup" # Adjust path if needed if you change install location
      become: no # IMPORTANT: Run as the user
    - name: Install alacritty
      import_tasks: alacritty.yaml
      tags:
        - packages
        - alacritty
    - name: Install NVM using the official script
      shell: |
        #!/bin/bash
        NVM_VERSION=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh" | bash
      args:
        executable: /bin/bash
        creates: "$HOME/.nvm/nvm.sh"
      become: no # Run as the user
    - name: Install Oh My Zsh using the official script
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        executable: /bin/bash # Ensure it runs with bash
        creates: "$HOME/.oh-my-zsh" # Make this task idempotent - check if the Oh My Zsh directory exists
      become: no # This script is designed to run as the user and install into the home directory
    - name: Set Zsh as the default shell for the user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}" # The user whose shell to change
        shell: /usr/bin/zsh # The path to the zsh executable
      become: yes # Need root privileges to change a user's default shell
    - name: Install Zed editor using the official script
      shell: |
        curl -f https://zed.dev/install.sh | sh
      args:
        executable: /bin/bash # Ensure it runs with bash
        creates: "$HOME/.local/bin/zed" # Make this task idempotent - check if the zed executable exists in the default install location
      become: no # This script is designed to run as the user and install into the home directory
    - name: Install chrome latest
      import_tasks: chrome.yaml
      tags:
        - packages
        - chrome
